#!/bin/bash
if [ $# -eq 2 ]
  then
    new=master
  else
    new=$3
fi;
TMPDIR=$(mktemp -d ./git-latexdiff.XXXXXX)
echo $TMPDIR
mkdir $TMPDIR
git checkout $2
latexpand "$1" --output $TMPDIR/diff1.tex
git checkout $new
latexpand "$1" --output $TMPDIR/diff2.tex
#git checkout master
latexdiff $TMPDIR/diff1.tex $TMPDIR/diff2.tex > $TMPDIR/diff.tex
pdflatex -interaction nonstopmode -output-directory $TMPDIR $TMPDIR/diff.tex
evince $TMPDIR/diff.pdf
rm -rf $TMPDIR

